### ISSUE TITLE
How to Calculate Parameters and  MultAdds？

### ISSUE THREAD

**Issue by sxpro** [nmhkahn/PCARN-pytorch#1]
I calculated the parameters and multasdds of your model, using https://github.com/sovrasov/flops-counter.pytorch. The results are different from yours. Can you provide your calculation method?

**Comment by nmhkahn** [comment]
Hi.
Referring to the MobileNet, we calculate the multadds using only the Conv2d layer. You can check the calculation method in [torchsummaryX](https://github.com/nmhkahn/torchsummaryX).

**Comment by sxpro** [comment]
from torchsummaryX import summary
import torch
from ecarn import Net
patch = 48
summary(Net(), torch.zeros((1, 3, patch, patch)))
#scale=4
The results: # Params:    1,111.90K # Mult-Adds: 3,635.29M
Can you provide more details? Thanks!

**Comment by sxpro** [comment]
> Hi.
> Referring to the MobileNet, we calculate the multadds using only the Conv2d layer. You can check the calculation method in [torchsummaryX](https://github.com/nmhkahn/torchsummaryX).

from torchsummaryX import summary
import torch
from ecarn import Net
patch = 48
summary(Net(), torch.zeros((1, 3, patch, patch)))
#scale=4
The results: # Params: 1,111.90K # Mult-Adds: 3,635.29M
Can you provide more details? Thanks!

**Comment by nmhkahn** [comment]
Maybe we miss the setting to produce the MultAdds in our paper.
When we calculate the MultAdds, use LR size as (320, 240) which makes HR as 720p (1280, 720).

And note that, params shown by the torchsummaryX can differ since it only counts the params that are passed through in the forward pass.
