### ISSUE TITLE
The results obtained are different from the paper

### ISSUE THREAD

**Issue by zpkosmos** [nmhkahn/PCARN-pytorch#4]
Thanks for your code!
I have some problem when test the results.
I download your results from the Google Drive and test them using LPIPS metric, but got different results from your paper
For example
The LPIPS result on Set5 **I got/in your paper** is
PCARN (L1): 0.1761/0.1769
PCARN-M (L1): 0.177/0.1793
PCARN: 0.0786/0.0745
PCARN-M: 0.0818/0.0796
Did you crop your results before test them or any other operation you did before testing.
Could you give me some instructions? Thank you!

**Comment by nmhkahn** [comment]
Hi @zpkosmos 
When we calculate LPIPS, we crop *scale_factor* pixels (e.g. 4 px for scale 4 and 2 px for scale 2).
I think we missed such kind of detailed evaluation in our paper so we will revise our paper.
Thanks!
