### ISSUE TITLE
The generator is trained with D_real_loss actually

### ISSUE THREAD

**Issue by Yeeef** [nmhkahn/PCARN-pytorch#5]
Hi,

When I went through your code, I found line 104 in `solver_gan.py` is weird. I think the parameter `is_real` should be False, since the image generated by Generator should be classified as Fake. Am I missing something?

Thanks in advance.

**Comment by nmhkahn** [comment]
Hi.
Since we want to guide "Generator" to make near-**real** images so we should let the discriminator that D(G(LR)) (which is `D_fake`, line 104) is **real** (`is_real=True`).
Check the [ESRGAN](https://github.com/xinntao/BasicSR/blob/master/codes/models/SRGAN_model.py#L156) code.

**Comment by Yeeef** [comment]
Thanks for your quick feedback! I understand now.
